#ifndef RUST_LIB_H
#define RUST_LIB_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct RenderContext RenderContext;

struct RenderContext *vello_ctx_create(uint32_t width, uint32_t height);

void vello_ctx_render(struct RenderContext *ctx_ptr, uint8_t *buffer, double time);

void vello_ctx_destroy(struct RenderContext *ctx_ptr);

#endif  /* RUST_LIB_H */
