#ifndef RUST_LIB_H
#define RUST_LIB_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

void render_vello_scene(uint8_t *buffer, uint32_t width, uint32_t height);

#endif  /* RUST_LIB_H */
